# Configuration for probot-stale - https://github.com/probot/stale

# Number of days of inactivity before an Issue or Pull Request becomes stale
daysUntilStale: 30
# Number of days of inactivity before a stale Issue or Pull Request is closed
daysUntilClose: 1095
# Issues or Pull Requests with these labels will never be considered stale. Set to `[]` to disable
exemptLabels:
  - kind/feature-request
  - severity/critical
  - severity/major
  - do-not-merge/HOLD
  - do-not-merge/WIP
  - community/help-wanted
# Label to use when marking as stale
staleLabel: stale
# Comment to post when marking as stale. Set to `false` to disable
markComment: >
  Thanks for your contribution!

  This issue has been automatically marked as stale because it has not had
  activity in the last 30 days. Note that the issue will not be automatically
  closed, but this notification will remind us to investigate why there's
  been inactivity. Thank you for participating in the Datadog open source community.

  If you would like this issue to remain open:

     1. Verify that you can still reproduce the issue in the latest version of this project.
     1. Comment that the issue is still reproducible and include updated details requested in the issue template.
# Comment to post when removing the stale label. Set to `false` to disable
unmarkComment: false
# Comment to post when closing a stale Issue or Pull Request. Set to `false` to disable
closeComment: false
# Limit to only `issues` or `pulls`
# only: pulls
